// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verso.Api;

#nullable disable

namespace Verso.Api.Persistence.Migrations
{
    [DbContext(typeof(VersoDbContext))]
    [Migration("20260530173708_AddCoverAssetCaching")]
    partial class AddCoverAssetCaching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Verso.Api.AudibleAuthenticationStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudibleAuthenticationStates", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemContributorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "Role", "Name")
                        .IsUnique();

                    b.ToTable("AudibleItemContributors", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemCoverImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CachedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CachedSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "Variant")
                        .IsUnique();

                    b.ToTable("AudibleItemCoverImages", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemEntity", b =>
                {
                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAudiblePayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Asin");

                    b.ToTable("AudibleItems", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemContributorEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("Contributors")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.AudibleItemCoverImageEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("CoverImages")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.AudibleItemEntity", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("CoverImages");
                });
#pragma warning restore 612, 618
        }
    }
}
