// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Verso.Api;

#nullable disable

namespace Verso.Api.Persistence.Migrations
{
    [DbContext(typeof(VersoDbContext))]
    partial class VersoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Verso.Api.AudibleAuthenticationStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudibleAuthenticationStates", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemContributorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "Role", "Name")
                        .IsUnique();

                    b.ToTable("AudibleItemContributors", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemCoverImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CachedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CachedSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "Variant")
                        .IsUnique();

                    b.ToTable("AudibleItemCoverImages", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemEntity", b =>
                {
                    b.Property<string>("Asin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCompanionPdf")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNoLongerPresent")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsReturnable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSeenInSuccessfulRefreshAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublisherSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAudiblePayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Asin");

                    b.ToTable("AudibleItems", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemSelectiveSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "Field", "ObservedAtUtc");

                    b.ToTable("AudibleItemSelectiveSnapshots", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemSeriesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudibleItemAsin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sequence")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AudibleItemAsin", "SortOrder")
                        .IsUnique();

                    b.ToTable("AudibleItemSeries", (string)null);
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservedItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhaseSummary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetainedNoLongerPresentItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotObservationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibraryRefreshJobs", (string)null);
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobErrorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRefreshJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalDetails")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRefreshJobId");

                    b.ToTable("LibraryRefreshJobErrors", (string)null);
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobPhaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryRefreshJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryRefreshJobId");

                    b.ToTable("LibraryRefreshJobPhases", (string)null);
                });

            modelBuilder.Entity("Verso.Api.AudibleItemContributorEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("Contributors")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.AudibleItemSelectiveSnapshotEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.AudibleItemCoverImageEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("CoverImages")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.AudibleItemSeriesEntity", b =>
                {
                    b.HasOne("Verso.Api.AudibleItemEntity", null)
                        .WithMany("Series")
                        .HasForeignKey("AudibleItemAsin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobErrorEntity", b =>
                {
                    b.HasOne("Verso.Api.LibraryRefreshJobEntity", null)
                        .WithMany("Errors")
                        .HasForeignKey("LibraryRefreshJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobPhaseEntity", b =>
                {
                    b.HasOne("Verso.Api.LibraryRefreshJobEntity", null)
                        .WithMany("Phases")
                        .HasForeignKey("LibraryRefreshJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Verso.Api.AudibleItemEntity", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("Series");

                    b.Navigation("Snapshots");
                    b.Navigation("CoverImages");
                });

            modelBuilder.Entity("Verso.Api.LibraryRefreshJobEntity", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
